export class Persional {
  userId?: string; // 用户ID
  username?: number; // 用户名
  password?: string; // 密码
  salt?: string; // 盐
  realName?: string; // 真实姓名
  sex?: string; // 性别
  birthday?: string; // 出生日期
  email?: string; // E-mail
  address?: string; // 地址
  mobilePhone?: string; // 手机号码
  enabled?: string; // 是否可用
  identity?: string; // 身份证号
  organizationId?: number; // 组织/机构ID
  organizationName?: string; // 组织/机构名字
  departmentId?: number; // 部门ID
  departmentName?: string; // 部门名字
  educationalBackground?: string; // 学历
  workingYears?: string; // 工龄
  hiredate?: string; // 入职时间
  nativePlace?: string; // 籍贯
  maritalStatus?: string; // 婚姻状况
  politicalStatus?: string; // 政治面貌
  volk?: string; // 名族
  technicalTitle?: string; // 职称
  remarks?: string; // 备注
  portraitPath?: string; // 头像路径
  loginStatus?: string; // 登陆状态
  newPassword?: string; // 登陆状态
  idt?: string; // 插入时间
  udt?: string; // 更新时间
}
